{{- if .Values.enabled }}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nvidia-dcgm-exporter
  namespace: {{ $.Values.namespace }}
spec:
  selector:
    matchLabels:
      name: nvidia-dcgm-exporter
  template:
    metadata:
      labels:
        app: nvidia-dcgm-exporter
      name: nvidia-dcgm-exporter
    spec:
{{- if .Values.initContainers }}
      initContainers:
        {{- toYaml .Values.initContainers | nindent 8 }}
{{- end }}
{{- if .Values.tolerations }}
      tolerations:
{{ toYaml .Values.tolerations | indent 8 }}
{{- end }}
      priorityClassName: {{ .Values.priorityClassName }}
      containers:
      - image: "{{ .Values.pod-nvidia-gpu-metrics-exporter.image.repository }}:{{ .Values.pod-nvidia-gpu-metrics-exporter.image.tag }}"
        name: pod-nvidia-gpu-metrics-exporter
        ports:
        - name: gpu-metrics
          containerPort: 9400
          hostPort: 9400
        securityContext:
          runAsNonRoot: false
          runAsUser: 0
        imagePullPolicy: {{ .Values.pod-nvidia-gpu-metrics-exporter.image.pullPolicy }}
        resources:
{{ toYaml .Values.pod-nvidia-gpu-metrics-exporter.resources | indent 12 }}
        volumeMounts:
        - name: pod-gpu-resources
          readOnly: true
          mountPath: /var/lib/kubelet/pod-resources
        - name: device-metrics
          readOnly: true
          mountPath: /run/prometheus
      - image: "{{ .Values.nvidia-dcgm-exporter.image.repository }}:{{ .Values.nvidia-dcgm-exporter.image.tag }}"
        name: nvidia-dcgm-exporter
        securityContext:
          runAsNonRoot: false
          runAsUser: 0
        imagePullPolicy: {{ .Values.nvidia-dcgm-exporter.image.pullPolicy }}
        resources:
{{ toYaml .Values.nvidia-dcgm-exporter.resources | indent 12 }}
        volumeMounts:
        - name: device-metrics
          mountPath: /run/prometheus
{{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
{{- end }}

      volumes:
      - name: pod-gpu-resources
        hostPath:
          path: /var/lib/kubelet/pod-resources
      - name: device-metrics
        emptyDir:
          medium: Memory
{{- end }}